[Service]
Environment="PATH=/opt/avops-docker/28.5.2:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
ExecStart=
ExecStart=/opt/avops-docker/28.5.2/dockerd --live-restore --data-root=/var/lib/docker --storage-driver=overlay2 --exec-opt native.cgroupdriver=cgroupfs
TimeoutStartSec=120
TimeoutStopSec=120
Restart=on-failure
RestartSec=5
