CREATE SCHEMA IF NOT EXISTS avops;
CREATE TABLE IF NOT EXISTS avops.schema_migrations(version integer PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS avops.documents(name text PRIMARY KEY, payload jsonb, encrypted_payload bytea, revision text NOT NULL DEFAULT '', updated_at timestamptz NOT NULL DEFAULT now(), CHECK ((payload IS NULL) <> (encrypted_payload IS NULL)));
CREATE TABLE IF NOT EXISTS avops.baseline_versions(revision text PRIMARY KEY, saved_at timestamptz NOT NULL, source text NOT NULL, definition jsonb NOT NULL, change jsonb NOT NULL, yaml text NOT NULL, extensions jsonb NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS avops.nodes(node_id text PRIMARY KEY, agent_id text NOT NULL, container_name text NOT NULL, cluster_code text NOT NULL, service_code text NOT NULL, restart_enabled boolean NOT NULL, active boolean NOT NULL, baseline_revision text NOT NULL REFERENCES avops.baseline_versions(revision), checks jsonb NOT NULL DEFAULT '[]', extensions jsonb NOT NULL DEFAULT '{}');
CREATE UNIQUE INDEX IF NOT EXISTS nodes_active_binding ON avops.nodes(agent_id,container_name) WHERE active;
CREATE INDEX IF NOT EXISTS nodes_service ON avops.nodes(cluster_code,service_code) WHERE active;
CREATE TABLE IF NOT EXISTS avops.operations(operation_id text PRIMARY KEY, request_key text NOT NULL UNIQUE, node_id text NOT NULL, agent_id text NOT NULL, status text NOT NULL, phase text NOT NULL, node_locked boolean NOT NULL, result_known boolean NOT NULL, requested_at timestamptz NOT NULL, finished_at timestamptz, authenticated_source text NOT NULL, source_ip text NOT NULL, operator text NOT NULL, reason text NOT NULL, payload jsonb NOT NULL, extensions jsonb NOT NULL DEFAULT '{}');
CREATE UNIQUE INDEX IF NOT EXISTS operations_active_node_lock ON avops.operations(node_id) WHERE node_locked;
CREATE INDEX IF NOT EXISTS operations_requested ON avops.operations(requested_at DESC,operation_id);
CREATE INDEX IF NOT EXISTS operations_state ON avops.operations(status,requested_at DESC);
CREATE TABLE IF NOT EXISTS avops.operation_audit(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, operation_id text NOT NULL REFERENCES avops.operations(operation_id), at timestamptz NOT NULL, kind text NOT NULL, payload jsonb NOT NULL);
CREATE INDEX IF NOT EXISTS operation_audit_lookup ON avops.operation_audit(operation_id,id);
CREATE TABLE IF NOT EXISTS avops.key_requests(request_id text PRIMARY KEY, name text NOT NULL, purpose text NOT NULL CHECK(purpose IN ('CONSOLE','RESTART')), reason text NOT NULL, status text NOT NULL, requested_at timestamptz NOT NULL, key_id text, payload jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS avops.access_keys(key_id text PRIMARY KEY, name text NOT NULL, purpose text NOT NULL CHECK(purpose IN ('CONSOLE','RESTART')), secret_hash text NOT NULL, enabled boolean NOT NULL, created_at timestamptz NOT NULL, owner_id text, payload jsonb NOT NULL, extensions jsonb NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS avops.key_node_scopes(key_id text NOT NULL REFERENCES avops.access_keys(key_id), node_id text NOT NULL, PRIMARY KEY(key_id,node_id));
CREATE TABLE IF NOT EXISTS avops.access_audit(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, at timestamptz NOT NULL, kind text NOT NULL, source text NOT NULL, payload jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS avops.notification_facts(fact_key text PRIMARY KEY,payload jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS avops.notification_events(event_id text PRIMARY KEY, occurred_at timestamptz NOT NULL, node_id text NOT NULL DEFAULT '', service_code text NOT NULL, status text NOT NULL, attempts integer NOT NULL, next_at timestamptz NOT NULL, settings_revision text NOT NULL DEFAULT '', payload jsonb NOT NULL);
CREATE INDEX IF NOT EXISTS notifications_pending ON avops.notification_events(next_at) WHERE status IN ('PENDING','INFLIGHT');
CREATE TABLE IF NOT EXISTS avops.notification_state(id boolean PRIMARY KEY DEFAULT true CHECK(id), revision text NOT NULL DEFAULT '', dropped bigint NOT NULL DEFAULT 0);
INSERT INTO avops.notification_state(id) VALUES(true) ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS avops.notification_audit(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, at timestamptz NOT NULL DEFAULT now(), payload jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS avops.agent_snapshots(agent_id text PRIMARY KEY,collected_at timestamptz NOT NULL,received_at timestamptz NOT NULL DEFAULT now(),payload jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS avops.containers(agent_id text NOT NULL,container_id text NOT NULL,container_name text NOT NULL,runtime_status text NOT NULL,image text NOT NULL,collected_at timestamptz NOT NULL,payload jsonb NOT NULL,PRIMARY KEY(agent_id,container_id));
CREATE INDEX IF NOT EXISTS containers_name ON avops.containers(container_name,agent_id);
CREATE INDEX IF NOT EXISTS containers_runtime ON avops.containers(runtime_status,agent_id);
CREATE TABLE IF NOT EXISTS avops.users(user_id text PRIMARY KEY,username text NOT NULL UNIQUE,display_name text NOT NULL,password_hash text NOT NULL,status text NOT NULL CHECK(status IN ('PENDING','ACTIVE','DISABLED')),reason text NOT NULL DEFAULT '',version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),extensions jsonb NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS avops.roles(role_id text PRIMARY KEY,name text NOT NULL UNIQUE,description text NOT NULL DEFAULT '',builtin boolean NOT NULL DEFAULT false,version integer NOT NULL DEFAULT 1,extensions jsonb NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS avops.permissions(code text PRIMARY KEY,name text NOT NULL);
CREATE TABLE IF NOT EXISTS avops.role_permissions(role_id text NOT NULL REFERENCES avops.roles(role_id),permission_code text NOT NULL REFERENCES avops.permissions(code),PRIMARY KEY(role_id,permission_code));
CREATE TABLE IF NOT EXISTS avops.user_roles(user_id text NOT NULL REFERENCES avops.users(user_id),role_id text NOT NULL REFERENCES avops.roles(role_id),PRIMARY KEY(user_id,role_id));
CREATE TABLE IF NOT EXISTS avops.sessions(token_hash text PRIMARY KEY,user_id text NOT NULL REFERENCES avops.users(user_id),created_at timestamptz NOT NULL DEFAULT now(),expires_at timestamptz NOT NULL,revoked boolean NOT NULL DEFAULT false);
CREATE INDEX IF NOT EXISTS sessions_expiration ON avops.sessions(expires_at);
CREATE TABLE IF NOT EXISTS avops.system_audit(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,at timestamptz NOT NULL DEFAULT now(),actor text NOT NULL,source_ip text NOT NULL,action text NOT NULL,target text NOT NULL,outcome text NOT NULL,details jsonb NOT NULL DEFAULT '{}');
CREATE INDEX IF NOT EXISTS system_audit_search ON avops.system_audit(at DESC,action,actor);
CREATE INDEX IF NOT EXISTS system_audit_login_rate ON avops.system_audit(source_ip,at DESC) WHERE action IN ('LOGIN_FAILED','REGISTER');
CREATE TABLE IF NOT EXISTS avops.import_batches(source_digest text PRIMARY KEY,imported_at timestamptz NOT NULL DEFAULT now(),manifest jsonb NOT NULL);
CREATE INDEX IF NOT EXISTS operations_payload_gin ON avops.operations USING gin(payload jsonb_path_ops);
CREATE INDEX IF NOT EXISTS baseline_definition_gin ON avops.baseline_versions USING gin(definition jsonb_path_ops);
CREATE INDEX IF NOT EXISTS containers_payload_gin ON avops.containers USING gin(payload jsonb_path_ops);
CREATE INDEX IF NOT EXISTS users_extensions_gin ON avops.users USING gin(extensions jsonb_path_ops);
INSERT INTO avops.schema_migrations(version) VALUES(1) ON CONFLICT DO NOTHING;
